contracts: use Majoolr TokenLib (first ever compile).
It's... alive?..

Implements #4.

Several "hidden" issues were fixed, most notably:

* minting actually being impossible due to `lastMintInvocationTime`
  being updated without saving `mintAllowance()` value first;

Also had to enable experimental "v0.5.0" syntax so otherToken
.transfer() method is not shadowed by address.transfer() override,
which, when coupled with forwarding of .gas(), made it fail:

solc.exceptions.SolcError: contracts/oobiqoo.sol:115:16: TypeError: Member "transfer" not unique after argument-dependent lookup in contract ERC20Interface
return otherToken.transfer.gas(msg.gas)(_to, _amount);
       ^-----------------^

Using Majoolr's TokenLib does mean that ERC20 functions must be
wrapped to use the `token` struct.

Likely to see further work.